config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get 'home/index'
  get 'home/staffMaster'
  get 'attendances/attendanceMaster/:start/:end' => 'attendances#attendanceMaster'
  get 'attendances/attendanceMaster/:start/:end/:dep' => 'attendances#attendanceMaster'
  get 'attendances/attendanceUser/:id/:start/:end' => 'attendances#attendanceUser'
  get 'attendances/attendanceUser/:id' => 'attendances#attendanceUser'
  get 'attendances/attendanceBook'
  delete 'attendances/attendanceDelete/:id' => 'attendances#attendanceDelete'
  get 'attendances/attendanceEdit/:id' => 'attendances#attendanceEdit'
  get 'attendances/attendanceNew/:user_id/:day' => 'attendances#attendanceNew'
  post 'attendances/attendanceUpdate'
  post 'attendances/attendanceCreate'
  get 'attendances/auto'
  post 'attendances/success'
  get 'attendances/success_in'
  get 'attendances/success_out'
  get 'attendances/error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :attendace
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable,:timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      added_attrs = [ :email, :name, :department, :wage, :password, :password_confirmation ]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    def attendanceBook
      if current_user.department == "本部"
        @attendacebook = Attendance.joins(:user).select('attendances.*, users.name')
      else
        redirect_to root_path
      end
    end
    def attendanceUser
      nowTime = Time.now.to_s(:db).to_datetime
      @nowTime = nowTime.strftime('%Y/%m/%d %H:%M:%S')
      @showUser = User.find_by(id: params[:id])
      if params[:start].nil? || params[:end].nil?
        @attendaceuser = Attendance.where(user_id: params[:id])
      else
        @attendaceuser = Attendance.where(user_id: params[:id], date: params[:start]..params[:end])
        require 'date'
        day = params[:start] 
        @dayStart = params[:start] 
        @day = day.to_date
        endDay = params[:end]
        @dayEnd = params[:end]
        @dayEndM = params[:end]
        @endDay = endDay.to_date
      end
    end
    def attendanceMaster
      nowTime = Time.now.to_s(:db).to_datetime
      @nowTime = nowTime.strftime('%Y/%m/%d %H:%M:%S')
      @userList = User.all
      if params[:start].nil? || params[:end].nil?
        @attendanceData = Attendance.all
      else
        @attendanceData = Attendance.where(date: params[:start]..params[:end])
        require 'date'
        day = params[:start] 
        @dayStart = params[:start] 
        @day = day.to_date
        endDay = params[:end]
        @dayEnd = params[:end]
        @dayEndM = params[:end]
        @endDay = endDay.to_date
      end
    end
    def attendanceEdit
      if  current_user.department == "本部"
      @attendanceEdit = Attendance.find_by(id: params[:id])
      session[:refererID] = request.referer
      else
        redirect_to root_path
      end
    end
    def attendanceNew
      if  current_user.department == "本部"
      session[:refererID] = request.referer
      else
        redirect_to root_path
      end
    end
    def attendanceCreate
      Attendance.create(user_id: params[:user_id], in: params[:in], out: params[:out], updater: params[:updater], date: params[:dateTo])
      redirect_to root_path
    end
    def attendanceUpdate
      @item = Attendance.find_by(id: params[:id])
      @item.update(in: params[:in],out: params[:out], updater: params[:updater])
      redirect_to session[:refererID]
    end
    def attendanceDelete
      Attendance.find_by(id: params[:id]).delete
      redirect_to request.referer
    end
    def success
        user = Attendance.order("id DESC").find_by(user_id: params[:user_id])
        staff = User.find_by(id: params[:user_id])
        nowTime = Time.now.to_s(:db)
        if staff.nil?
            flash[:alert] = "無効なスタッフです"
            redirect_to attendances_error_path
        else
          if user.nil? || user.date.to_s != Date.current.strftime("%Y-%m-%d")
            Attendance.create({user_id: params[:user_id], in: nowTime, date: nowTime.slice!(0..9), updater: staff.name})
            redirect_to attendances_success_in_path
          else  
            user.update(out: nowTime, updater: staff.name)
            redirect_to attendances_success_out_path
          end
        end
    end
    
    def error
      youbi = %w[日曜日 月曜日 火曜日 水曜日 木曜日 金曜日 土曜日 日曜日]
      @date = Date.current.strftime("%Y年 %m月 %d日") + "( " +youbi[Date.today.wday] + " )"
    end
    def attendance_params
      params.permit(:user_id)
    end
    def auto
      youbi = %w[日曜日 月曜日 火曜日 水曜日 木曜日 金曜日 土曜日 日曜日]
      @date = Date.current.strftime("%Y年 %m月 %d日") + "( " +youbi[Date.today.wday] + " )"
      @time = Time.now
    end
    def success_in
        youbi = %w[日曜日 月曜日 火曜日 水曜日 木曜日 金曜日 土曜日 日曜日]
        @date = Date.current.strftime("%Y年 %m月 %d日") + "( " +youbi[Date.today.wday] + " )"
    end  
    def success_out
        youbi = %w[日曜日 月曜日 火曜日 水曜日 木曜日 金曜日 土曜日 日曜日]
        @date = Date.current.strftime("%Y年 %m月 %d日") + "( " +youbi[Date.today.wday] + " )"
    end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    user = Attendance.order("id DESC").find_by(user_id: current_user.id)
    if  user.nil?
    elsif user.date.to_s == Date.current.strftime("%Y-%m-%d")
        @attendanceMy = user
    end
    @date = Date.current.strftime("%Y年 %m月 %d日")
    @time = Time.now
  end
  def staffMaster
    if  current_user.department == "本部"
    @staffs = User.all
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    require 'rqrcode'
    require 'rqrcode_png'

    def qrcode(text, options = {})
        ::RQRCode::QRCode.new(text, options).as_svg.html_safe
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendances/attendanceBook.html.erb
<div class="Page-Area">
<div class="Page-Title">
勤務打刻時間マスター
</div>
<div class="Page-Text">
全従業員の勤務時間打刻が確認可能です
</div>
<div class="DashBoard">
<table class="table">
  <thead>
    <tr>
      <th>打刻対象ID</th>
      <th>打刻対象氏名</th>
      <th>出勤打刻日時</th>
      <th>退勤打刻日時</th>
      <th>勤務時間</th>
      <th>手当</th>
      <th>最終更新者</th>
      <th>修正・取消</th>
    </tr>
  </thead>
  <tbody>
  <% if @attendacebook.present?%>
  <% i = 1%>
    <% @attendacebook.each do |attendance| %>
      <% if attendance.out.nil?%>
        <%attendanceOut = @nowTime %>
      <%else%>
        <%attendanceOut = attendance.out.strftime('%Y/%m/%d %H:%M:%S') %>
        <%attendanceOutValue = attendance.out %>
      <%end%>
      <tr>
        <td><%= format("%04d", attendance.user_id) %></td>
        <td><%= attendance.name %></td>
        <% if attendance.in.nil? %>
        <td>打刻エラー</td>
        <% else %>
        <td><%= attendance.in.strftime('%Y/%m/%d %H:%M:%S') %></td>
        <% end %>
        <% if attendance.out.nil? %>
        <td>打刻エラー</td>
        <td>勤務中</td>
        <% else %>
        <td><%= attendance.out.strftime('%Y/%m/%d %H:%M:%S') %></td>
        <td><%= (sprintf("%.1f",(attendanceOutValue.to_f - attendance.in.to_f).floor / 60 /60.to_f)) %></td>
        <% end %>
        <td><%= attendance.benefit.presence || 0 %></td>
        <td><%= attendance.updater %></td>
        <td><%= link_to("修正", "/attendances/attendanceEdit/#{attendance.id}",class:"btn btn-sm btn-primary") %> <%= link_to("取消", "/attendances/attendanceDelete/#{attendance.id}",class:"btn btn-sm btn-danger", method: :delete) %></td>
      </tr>
      <% i += 1%>
    <% end %>
  <% end %>
  </tbody>
</table>
</div>
</div>
<%= link_to "アカウント情報編集", edit_user_registration_path, class: "user-edit-btn" %>

app/views/attendances/attendanceEdit.html.erb
<div class="Page-Area">
<div class="Page-Title">
勤務打刻時間修正
</div>
<div class="Page-Text">
対象の勤務時間打刻を修正可能です
</div>
<div class="DashBoard">
<div class="DashBoard-Title">
打刻修正
</div>
<%= form_with(model: @attendance, url: {controller: 'attendances', action: 'attendanceUpdate'}) do |f| %>
  <div class="field">
    <%= f.hidden_field :id,:value =>@attendanceEdit.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :updater,:value =>current_user.name %>
  </div>
  <div class="form-group">
    <%= f.label :出勤時刻 %><br />
    <%= f.text_field :in, autofocus: false, class: "form-control",:value =>@attendanceEdit.in %>
  </div>
  <div class="form-group">
    <%= f.label :退勤時刻 %><br />
    <%= f.text_field :out, autofocus: false, class: "form-control",:value =>@attendanceEdit.out %>
  </div>
  <div class="form-group">
  <%= f.submit "修正", class: 'Submit-btn' %>
  </div>
<% end %>
</div>
<div class="DashBoard">
<div class="DashBoard-Title">
打刻情報
</div>
<table class="table">
  <thead>
    <tr>
      <th>打刻対象ID</th>
      <th>打刻対象氏名</th>
      <th>出勤打刻日時</th>
      <th>退勤打刻日時</th>
      <th>勤務時間</th>
      <th>手当</th>
      <th>最終更新者</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= format("%04d", @attendanceEdit.user_id) %></td>
      <td><%= @attendanceEdit.updater %></td>
      <% if @attendanceEdit.in.nil? %>
      <td>打刻エラー</td>
      <% else %>
      <td><%= @attendanceEdit.in.strftime('%Y/%m/%d %H:%M:%S') %></td>
      <% end %>
      <% if @attendanceEdit.out.nil? %>
      <td>打刻エラー</td>
      <td>勤務中</td>
      <% else %>
      <td><%= @attendanceEdit.out.strftime('%Y/%m/%d %H:%M:%S') %></td>
      <td><%= sprintf("%.1f",(@attendanceEdit.out - @attendanceEdit.in).floor / 60 /60.to_f) %></td>
      <% end %>
      <td><%= @attendanceEdit.benefit.presence || 0 %></td>
      <td><%= @attendanceEdit.updater %></td>
    </tr>
  </tbody>
</table>
</div>
</div>

app/views/attendances/attendanceMaster.html.erb
<div class="Page-Area">
  <div class="Page-Title">
  給与マスター
  </div>
  <div class="Page-Text">
  以下期間の給与マスターを確認できます。<br>
  <% if !(params[:start].nil?) %>
  対象期間：<%= params[:start] %> 〜 <%= params[:end] %><br>
  <%end%>
  <% if !(params[:dep].nil?) %>
  部署：<%= params[:dep] %>
  <%end%>
  </div>

<div class="DashBoard">
<table class="table">
  <thead>
    <th>氏名</th>
    <% day = @day  %>
    <% endDay = @endDay  %>
    <% totalWage = 0%>
    <% while endDay >= day do %>
    <th> <%= day.strftime('%m/%d') %> </th>
    <% day += 1 %>
    <% end %>
    <th>残業時間</th>
  </thead>

    <% i = 1%>
    <% @userList.each do |user| %>
    <% totalJob = 0 %>
    <tbody>
    <td><%= user.name %></td>
    <% a = 1%>
    <% @attendanceData.each do |attendance| %>
      <% day = @day %>
      <% while endDay >= day do %>
      <% if attendance.date == day && attendance.user_id == user.id && !(attendance.out.nil?) %>
        <% touchTime = sprintf("%.1f",(attendance.out.to_f - attendance.in.to_f).floor / 60 /60.to_f).to_f %>
        <% if touchTime < 6.to_f && touchTime > 5.to_f%>
          <% lestTime = 0.5.to_f%>
        <%elsif touchTime > 5.9.to_f%>
          <% lestTime = 1.to_f%>
        <%else%>
        <% lestTime = 0.to_f%>
      <% end %>
      <% jobTime = touchTime.to_f - lestTime.to_f%>
      <% if jobTime.to_f > 8.to_f %>
        <td><%= jobTime - (jobTime.to_f - 8.to_f) %></td>
        <% overTime = jobTime.to_f - 8.to_f %>
      <%else%>
        <td><%= jobTime %></td>
        <% overTime = 0.to_f %>
      <% end %>
      <% totalJob = overTime + totalJob %>
      <% end %>
      <% day += 1 %>
      <% end %>
      <td></td>
    <% end %>
    <td><%= totalJob %></td>
    </tbody>
  <% end %>

</table>

</div>

app/views/attendances/attendanceNew.html.erb
<div class="Page-Area">
<div class="Page-Title">
勤務打刻時間登録
</div>
<div class="Page-Text">
対象の勤務時間打刻を追加登録可能です
</div>
<div class="DashBoard">
<div class="DashBoard-Title">
打刻登録
</div>
<%= form_with(model: @attendance, url: {controller: 'attendances', action: 'attendanceCreate'}) do |f| %>
  <div class="field">
    <%= f.hidden_field :user_id,:value =>params[:user_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :dateTo,:value =>params[:day] %>
  </div>
  <div class="field">
    <%= f.hidden_field :updater,:value =>current_user.name %>
  </div>
  <div class="form-group">
    <%= f.label :出勤時刻 %><br />
    <%= f.text_field :in, autofocus: false, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :退勤時刻 %><br />
    <%= f.text_field :out, autofocus: false, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.submit "登録", class: 'Submit-btn' %>
  </div>
<% end %>
</div>
</div>

app/views/attendances/attendanceUser.html.erb
<%if current_user.id == @showUser.id || current_user.department == "本部"%>
<%else%>
  <meta http-equiv="refresh" content="0;URL=http://52.68.140.65/">
<%end%>
<div class="Page-Area">
<div class="Page-Title">
<%= @dayEndM.slice!5..6 %>月 支払い勤務実績表
</div>
<div class="Page-Text">
<%= @showUser.name %>様の勤務時間打刻が確認可能です<br>
</div>
<div class="DashBoard">
<table class="table">
  <thead>
    <tr>
      <th>日付</th>
      <%if current_user.department == "本部"%>
      <th>追加</th>
      <% end %>
      <th>出勤時間</th>
      <th>退勤時間</th>
      <th>労働時間</th>
      <th>残業時間</th>
      <th>休憩時間</th>
      <th>見込み給与</th>
      <th>最終更新者</th>
      <th>修正・取消</th>
    </tr>
  </thead>
  <% if @attendaceuser.present?%>
  <% day = @day  %>
  <% endDay = @endDay  %>
  <% totalWage = 0%>
  <% while endDay >= day do %>
    <tbody>
    <td><%= day %></td>
    <%if current_user.department == "本部"%>
    <td><%= link_to("+", "/attendances/attendanceNew/#{@showUser.id}/#{day}",class:"btn btn-sm btn-primary") %></td>
    <% end %>
  <% j = 1%>
    <% @attendaceuser.each do |attendance| %>
      <% if attendance.date == day%>
        <% if attendance.out.nil?%>
          <%attendanceOut = @nowTime %>
        <%else%>
          <%attendanceOut = attendance.out.strftime('%Y/%m/%d %H:%M:%S') %>
          <%attendanceOutValue = attendance.out %>
        <%end%>
        <% touchTime = sprintf("%.1f",(attendanceOutValue.to_f - attendance.in.to_f).floor / 60 /60.to_f).to_f %>
        <% if touchTime < 6.to_f && touchTime > 5.to_f%>
          <% lestTime = 0.5.to_f%>
        <%elsif touchTime > 5.9.to_f%>
          <% lestTime = 1.to_f%>
        <%else%>
          <% lestTime = 0.to_f%>
        <% end %>
        <% jobTime = touchTime.to_f - lestTime.to_f%>
        <% if attendance.in.nil? %>
          <td>打刻エラー</td>
        <% else %>
          <td><%= attendance.in.strftime('%Y/%m/%d %H:%M:%S') %></td>
        <% end %>
        <% if attendanceOut.nil? %>
          <td>打刻エラー</td>
          <td>勤務中</td>
        <% else %>
          <td><%= attendanceOut %></td>
          <% if jobTime.to_f > 8.to_f %>
            <td><%= jobTime - (jobTime.to_f - 8.to_f) %></td>
            <td><%= jobTime.to_f - 8.to_f %></td>
            <% overTime = jobTime.to_f - 8.to_f %>
          <%else%>
            <td><%= jobTime %></td>
            <td>0</td>
            <% overTime = 0.to_f %>
          <% end %>
        <% end %>
        <td><%= lestTime %></td>
        <% if jobTime.to_f > 0.to_f %>
        <td>約<%= (((jobTime.to_f  - overTime ) * @showUser.wage.to_f) + overTime * (1.25.to_f * @showUser.wage.to_f)).to_i %>円</td>
        <% totalWage += (((jobTime.to_f  - overTime ) * @showUser.wage.to_f) + overTime * (1.25.to_f * @showUser.wage.to_f)).to_i%>
        <% else %>
        <td>0円</td>
        <% end %>
        <td><%= attendance.updater.presence || 0 %></td>
        <%if current_user.department == "本部"%>
        <td><%= link_to("修正", "/attendances/attendanceEdit/#{attendance.id}",class:"btn btn-sm btn-primary") %> <%= link_to("取消", "/attendances/attendanceDelete/#{attendance.id}",class:"btn btn-sm btn-danger", method: :delete) %></td>
        <%else%>
        <td></td>
        <%end%>
        <% end %>
              <% j += 1%>
        <% lestTime = 0%>
        <% touchTime = 0 %>
        <% jobTime = 0 %>
    <% end %>
    </tbody>
    <% day += 1 %>

  <% end %>
  <% end %>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td>見込み給与合計</td>
  <td>約<%= totalWage %>円</td>
</table>
</div>
</div>

app/views/attendances/auto.html.erb
<script>
    function twoDigit(num) {
        let ret;
        if (num < 10)
            ret = "0" + num;
        else
            ret = num;
        return ret;
    }
    function showClock() {
        let nowTime = new Date();
        let nowHour = twoDigit(nowTime.getHours());
        let nowMin = twoDigit(nowTime.getMinutes());
        let nowSec = twoDigit(nowTime.getSeconds());
        let msg = nowHour + ":" + nowMin + ":" + nowSec;
        document.getElementById("realtime").innerHTML = msg;
    }
    setInterval('showClock()', 1000);

</script>

<body onload="document.getElementById('form-control').focus(); LoadProc();" style="background-color:#2d2d2d;">
	<div class="date">
        <%= @date %>
	</div>
	<div class="time">
		<a id="realtime"><%= @time.strftime("%H:%M:%S") %></a>
	</div>
	<div class="cate">
		Process：
	</div>
	<div class="cate-text-A">
		自動判別
	</div>
    <%= form_with(model: @attendances, url: {controller: 'attendances', action: 'success'}) do |f| %>
		<%= f.text_field :user_id, required: true, autofocus: true, placeholder: "" %>
    <% end %>
	
</body>

app/views/attendances/error.html.erb
<meta http-equiv="Refresh" content="1.5; url=<%= request.referer %>">
<%= audio_tag"error.mp3", autoplay: true, controls: false %>
<body onload="document.getElementById('form-control').focus(); LoadProc();" style="background-color:#2d2d2d;">
	<div class="date">
		<%= @date %>
	</div>
	<div class="time">
		(ﾟДﾟ≡ﾟДﾟ)?
	</div>
	<div class="cate">
		Process：
	</div>
	<div class="cate-text-E">
		ERROR
	</div>
	
</body>

app/views/attendances/success.html.erb
<meta http-equiv="Refresh" content="1.5; url=<%= request.referer %>">
<%= audio_tag"/audio/success.mp3", autoplay: true, controls: false %>
<script>
    function twoDigit(num) {
        let ret;
        if( num < 10 ) 
        ret = "0" + num; 
        else 
        ret = num; 
        return ret;
    }
    function showClock() {
        let nowTime = new Date();
        let nowHour = twoDigit( nowTime.getHours() );
        let nowMin  = twoDigit( nowTime.getMinutes() );
        let nowSec  = twoDigit( nowTime.getSeconds() );
        let msg =  nowHour + ":" + nowMin + ":" + nowSec;
        document.getElementById("realtime").innerHTML = msg;
    }
    setInterval('showClock()',1000);
</script>

<body onload="document.getElementById('form-control').focus(); LoadProc();" style="background-color:#2d2d2d;">
	<div class="date">
		<script language="JavaScript">
		mydate=new Date();
		Ye=mydate.getFullYear()+"年";
		Mo=mydate.getMonth()+1+"月";
		Da=mydate.getDate()+"日";
		Day=mydate.getDay();
		Day2=new Array(7);
		Day2[0]="日";Day2[1]="月";Day2[2]="火";
		Day2[3]="水";Day2[4]="木";Day2[5]="金";
		Day2[6]="土";
		document.write(Ye+Mo+Da+"（"+Day2[Day]+"）");
		</script>
	</div>
	<div class="time">
		(·:ﾟдﾟ:·)ﾊｧﾊｧ
	</div>
	<div class="cate">
		Process：
	</div>
	<div class="cate-text-S">
		SUCCESS
	</div>
	
</body>

app/views/attendances/success_in.html.erb
<meta http-equiv="Refresh" content="1.5; url=<%= request.referer %>">
<%= audio_tag"in.mp3", autoplay: true, controls: false %>
<body onload="document.getElementById('form-control').focus(); LoadProc();" style="background-color:#2d2d2d;">
	<div class="date">
	<%= @date %>
	</div>
	<div class="time">
		(·:ﾟдﾟ:·)ﾊｧﾊｧ
	</div>
	<div class="cate">
		Process：
	</div>
	<div class="cate-text-I-S">
		出勤
	</div>
</body>

app/views/attendances/success_out.html.erb
<meta http-equiv="Refresh" content="1.5; url=<%= request.referer %>">
<%= audio_tag"out.mp3", autoplay: true, controls: false %>
<body onload="document.getElementById('form-control').focus(); LoadProc();" style="background-color:#2d2d2d;">
	<div class="date">
	<%= @date %>
	</div>
	<div class="time">
		(·:ﾟдﾟ:·)ﾊｧﾊｧ
	</div>
	<div class="cate">
		Process：
	</div>
	<div class="cate-text-O-S">
		退勤
	</div>
	
</body>

app/views/home/index.html.erb
<script>
    function twoDigit(num) {
        let ret;
        if (num < 10)
            ret = "0" + num;
        else
            ret = num;
        return ret;
    }
    function showClock() {
        let nowTime = new Date();
        let nowHour = twoDigit(nowTime.getHours());
        let nowMin = twoDigit(nowTime.getMinutes());
        let nowSec = twoDigit(nowTime.getSeconds());
        let msg = nowHour + ":" + nowMin + ":" + nowSec;
        document.getElementById("realtime").innerHTML = msg;
    }
    setInterval('showClock()', 1000);

</script>
<div class="DashBoard-Top-TimeCard">
<div class="DashBoard-Top-TimeCard-Title">
- Time Card -
</div>
<div class="DashBoard-Top-TimeCard-QRArea">
<%= qrcode format("%06d", current_user.id), {size: 2,  level: :h} %>
</div>
<div class="DashBoard-Top-TimeCard-Time">
<%= @date %> <a id="realtime"><%= @time.strftime("%H:%M:%S") %></a>
</div>
<div class="DashBoard-Top-TimeCard-Line double"></div>
<div class="DashBoard-Top-TimeCard-Text">
所属：<%= current_user.department %>（新生ビルテクノ株式会社 / 稲毛海浜公園プール）
</div>
<div class="DashBoard-Top-TimeCard-Line dashed"></div>
<div class="DashBoard-Top-TimeCard-Text Title">
氏名：<%= current_user.name %>
</div>
<div class="DashBoard-Top-TimeCard-Line dashed"></div>
<% if @attendanceMy.nil? %>
    <div class="DashBoard-Top-TimeCard-Status">
    未出勤
    </div>
<% elsif @attendanceMy.out.nil? %>
    <div class="DashBoard-Top-TimeCard-Status Active">
    出勤中 ( 出勤打刻：<%= @attendanceMy.in.strftime('%Y/%m/%d %H:%M:%S') %> )
    </div>
<% else %>
    <div class="DashBoard-Top-TimeCard-Status Active">
    退勤済 ( 退勤打刻：<%= @attendanceMy.out.strftime('%Y/%m/%d %H:%M:%S') %> )
    </div>
<% end %>
</div>

<div class="Dashboard-DoubleGroup">
    <div class="Select-botun-home">
    <%= link_to("勤怠確認", "attendances/attendanceUser/#{current_user.id}/2022-08-11/2022-09-10") %>
    </div>
    <div class="Select-botun-home">
    <%= link_to "勤怠マスタ", attendances_attendanceBook_path %>
    </div>
    <div class="Select-botun-home">
    <%= link_to "スタッフマスタ", home_staffMaster_path %>
    </div>
</div>

<%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RAKUKIN | クラウド型勤怠管理サービス</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
  <% unless current_page?(attendances_auto_path) %>
    <%= render 'devise/shared/header' %>
  <% end %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
      <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>